[tool.poetry]
name = "repl_python3_cs9-final-project-hccs-ewang"
version = "0.1.0"
description = ""
authors = ["EugeneWang2 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
